@startuml
'https://plantuml.com/sequence-diagram

 package Equipo{
 class Equipo{
  ~List<Jugador> database
 }

 }
 package Jugador{
 Class Jugador{
  -String name
  -String apellido
  -int Posicion
  -int numero
 }
 }

Equipo "1" -- "*"Jugador
Equipo o-- Jugador

@enduml