@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Cartas.Cartas",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2011245426 { 
   	label=Cartas
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Cartas2011245426[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cartas</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   numero: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   palo: Palo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   paloClass: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_502329872 { 
   	label=CartasServices
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CartasServices502329872[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CartasServices</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   CartasMonton: ArrayList&lt;Cartas&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   cartasDataBase: ArrayList&lt;Cartas&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ barajar()</TD></TR>
<TR><TD ALIGN="LEFT" >+ darCartas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ llenar()</TD></TR>
<TR><TD ALIGN="LEFT" >+ recorrerDataBase()</TD></TR>
<TR><TD ALIGN="LEFT" >+ siguienteCarta()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
CartasServices502329872 -> Cartas2011245426[label="CartasMonton
[0..*]"];
CartasServices502329872 -> Cartas2011245426[label="cartasDataBase
[0..*]"];
    
}
@enduml