@startuml
'https://plantuml.com/sequence-diagram

package Perro{
   class perro{
      -nombre
      -raza
      -edad
      -tamaño
   }
}
package Persona{
   class persona{
      -nombre
      -apellido
      -edad
      -documento
      -Perro perro
   }
}
persona "1" o-- "1" perro
@enduml